ACCEPT ACHIEVEMENT_ID NUMBER PROMPT 'Achievement ID: '
ACCEPT PLAYER_ID NUMBER PROMPT 'Player ID: '
ACCEPT TOURNAMENT_ID NUMBER PROMPT 'Tournament ID: '
ACCEPT POSITION CHAR PROMPT 'Position: '

INSERT INTO ACHIEVEMENT VALUES (&ACHIEVEMENT_ID, &PLAYER_ID, &TOURNAMENT_ID, '&POSITION');
COMMIT;
PROMPT Achievement added successfully.
