ACCEPT ACHIEVEMENT_ID NUMBER PROMPT 'Achievement ID to update: '
ACCEPT NEW_POSITION CHAR PROMPT 'New position: '

UPDATE ACHIEVEMENT SET POSITION = '&NEW_POSITION' WHERE ACHIEVEMENT_ID = &ACHIEVEMENT_ID;
COMMIT;
PROMPT Achievement updated successfully.
