COLUMN PLAYER_NAME FORMAT A25
COLUMN TOURNAMENT_NAME FORMAT A30
COLUMN POSITION FORMAT A10

SELECT A.ACHIEVEMENT_ID, A.PLAYER_ID, P.PLAYER_NAME, A.TOURNAMENT_ID, T.TOURNAMENT_NAME, A.POSITION
FROM ACHIEVEMENT A
JOIN PLAYER P ON P.PLAYER_ID = A.PLAYER_ID
JOIN TOURNAMENT T ON T.TOURNAMENT_ID = A.TOURNAMENT_ID
ORDER BY A.ACHIEVEMENT_ID;
