ACCEPT ADMISSION_ID NUMBER PROMPT 'Admission ID to update: '
ACCEPT NEW_DATE CHAR PROMPT 'New admission date (DD-MM-YYYY): '

UPDATE ADMISSION
SET ADMISSION_DATE = TO_DATE('&NEW_DATE', 'DD-MM-YYYY')
WHERE ADMISSION_ID = &ADMISSION_ID;
COMMIT;
PROMPT Admission updated successfully.
