ACCEPT ADMISSION_ID NUMBER PROMPT 'Admission ID to search: '

COLUMN PLAYER_NAME FORMAT A25
COLUMN SPORT_NAME FORMAT A20

SELECT A.ADMISSION_ID, A.PLAYER_ID, P.PLAYER_NAME, A.SPORT_ID, S.SPORT_NAME, A.ADMISSION_DATE
FROM ADMISSION A
JOIN PLAYER P ON P.PLAYER_ID = A.PLAYER_ID
JOIN SPORT S ON S.SPORT_ID = A.SPORT_ID
WHERE A.ADMISSION_ID = &ADMISSION_ID;
