ACCEPT ADMISSION_ID NUMBER PROMPT 'Admission ID: '
ACCEPT PLAYER_ID NUMBER PROMPT 'Player ID: '
ACCEPT SPORT_ID NUMBER PROMPT 'Sport ID: '
ACCEPT ADMISSION_DATE CHAR PROMPT 'Admission date (DD-MM-YYYY): '

INSERT INTO ADMISSION VALUES (&ADMISSION_ID, &PLAYER_ID, &SPORT_ID, TO_DATE('&ADMISSION_DATE', 'DD-MM-YYYY'));
COMMIT;
PROMPT Admission added successfully.
