ACCEPT COACH_ID NUMBER PROMPT 'Coach ID: '
ACCEPT COACH_NAME CHAR PROMPT 'Coach name: '
ACCEPT EXPERIENCE NUMBER PROMPT 'Experience: '
ACCEPT CONTACT_NO CHAR PROMPT 'Contact no: '
ACCEPT SALARY NUMBER PROMPT 'Salary: '

INSERT INTO COACH VALUES (&COACH_ID, '&COACH_NAME', &EXPERIENCE, '&CONTACT_NO', &SALARY);
COMMIT;
PROMPT Coach added successfully.
