COLUMN PLAYER_NAME FORMAT A25
COLUMN GENDER FORMAT A10
COLUMN CONTACT_NO FORMAT A15
COLUMN SPORT_NAME FORMAT A20

SELECT P.PLAYER_ID, P.PLAYER_NAME, P.AGE, P.GENDER, P.CONTACT_NO, S.SPORT_NAME
FROM PLAYER P
LEFT JOIN SPORT S ON S.SPORT_ID = P.SPORT_ID
ORDER BY P.PLAYER_ID;
