ACCEPT PLAYER_ID NUMBER PROMPT 'Player ID to update: '
ACCEPT NEW_NAME CHAR PROMPT 'New player name: '

UPDATE PLAYER SET PLAYER_NAME = '&NEW_NAME' WHERE PLAYER_ID = &PLAYER_ID;
COMMIT;
PROMPT Player updated successfully.
