ACCEPT PLAYER_ID NUMBER PROMPT 'Player ID: '
ACCEPT PLAYER_NAME CHAR PROMPT 'Player name: '
ACCEPT AGE NUMBER PROMPT 'Age: '
ACCEPT GENDER CHAR PROMPT 'Gender: '
ACCEPT CONTACT_NO CHAR PROMPT 'Contact no: '
ACCEPT SPORT_ID NUMBER PROMPT 'Sport ID: '

INSERT INTO PLAYER VALUES (&PLAYER_ID, '&PLAYER_NAME', &AGE, '&GENDER', '&CONTACT_NO', &SPORT_ID);
COMMIT;
PROMPT Player added successfully.
