ACCEPT LOCATION CHAR PROMPT 'Location: '

COLUMN TOURNAMENT_NAME FORMAT A30
COLUMN LOCATION FORMAT A20

SELECT TOURNAMENT_ID, TOURNAMENT_NAME, LOCATION, TOURNAMENT_DATE
FROM TOURNAMENT
WHERE UPPER(LOCATION) = UPPER('&LOCATION')
ORDER BY TOURNAMENT_DATE;
