COLUMN PLAYER_NAME FORMAT A25
COLUMN SPORT_NAME FORMAT A20
COLUMN SCHEDULE FORMAT A15

SELECT P.PLAYER_ID, P.PLAYER_NAME, P.AGE, P.GENDER, S.SPORT_NAME, S.FEES, S.SCHEDULE
FROM PLAYER P
JOIN SPORT S ON S.SPORT_ID = P.SPORT_ID
ORDER BY P.PLAYER_ID;
