PROMPT
PROMPT REPORTS
PROMPT 1. PLAYERS WITH SPORTS
PROMPT 2. ADMISSIONS WITH PLAYERS AND SPORTS
PROMPT 3. ACHIEVEMENTS WITH TOURNAMENTS
PROMPT 4. TOURNAMENTS BY LOCATION
PROMPT

ACCEPT CHOICE NUMBER PROMPT 'Enter report choice: '

COLUMN REPORT_SCRIPT NEW_VALUE REPORT_SCRIPT NOPRINT
SELECT CASE &CHOICE
          WHEN 1 THEN 'report_players.sql'
          WHEN 2 THEN 'report_admissions.sql'
          WHEN 3 THEN 'report_achievements.sql'
          WHEN 4 THEN 'report_tournaments.sql'
          ELSE 'invalidmenu.sql'
       END REPORT_SCRIPT
FROM DUAL;

@@&REPORT_SCRIPT
