COLUMN PLAYER_NAME FORMAT A25
COLUMN TOURNAMENT_NAME FORMAT A30
COLUMN LOCATION FORMAT A20
COLUMN POSITION FORMAT A10

SELECT P.PLAYER_NAME, T.TOURNAMENT_NAME, T.LOCATION, T.TOURNAMENT_DATE, A.POSITION
FROM ACHIEVEMENT A
JOIN PLAYER P ON P.PLAYER_ID = A.PLAYER_ID
JOIN TOURNAMENT T ON T.TOURNAMENT_ID = A.TOURNAMENT_ID
ORDER BY T.TOURNAMENT_DATE, A.POSITION;
