ACCEPT SPORT_ID NUMBER PROMPT 'Sport ID: '
ACCEPT SPORT_NAME CHAR PROMPT 'Sport name: '
ACCEPT FEES NUMBER PROMPT 'Fees: '
ACCEPT SCHEDULE CHAR PROMPT 'Schedule: '

INSERT INTO SPORT VALUES (&SPORT_ID, '&SPORT_NAME', &FEES, '&SCHEDULE');
COMMIT;
PROMPT Sport added successfully.
