ACCEPT TOURNAMENT_ID NUMBER PROMPT 'Tournament ID: '
ACCEPT TOURNAMENT_NAME CHAR PROMPT 'Tournament name: '
ACCEPT LOCATION CHAR PROMPT 'Location: '
ACCEPT TOURNAMENT_DATE CHAR PROMPT 'Tournament date (DD-MM-YYYY): '

INSERT INTO TOURNAMENT VALUES (&TOURNAMENT_ID, '&TOURNAMENT_NAME', '&LOCATION', TO_DATE('&TOURNAMENT_DATE', 'DD-MM-YYYY'));
COMMIT;
PROMPT Tournament added successfully.
