ACCEPT TOURNAMENT_ID NUMBER PROMPT 'Tournament ID to update: '
ACCEPT NEW_LOCATION CHAR PROMPT 'New location: '

UPDATE TOURNAMENT SET LOCATION = '&NEW_LOCATION' WHERE TOURNAMENT_ID = &TOURNAMENT_ID;
COMMIT;
PROMPT Tournament updated successfully.
