SET ECHO ON

DROP TABLE ACHIEVEMENT CASCADE CONSTRAINTS;
DROP TABLE ADMISSION CASCADE CONSTRAINTS;
DROP TABLE PLAYER CASCADE CONSTRAINTS;
DROP TABLE COACH CASCADE CONSTRAINTS;
DROP TABLE TOURNAMENT CASCADE CONSTRAINTS;
DROP TABLE SPORT CASCADE CONSTRAINTS;

CREATE TABLE SPORT (
   SPORT_ID NUMBER(5) PRIMARY KEY,
   SPORT_NAME VARCHAR2(30) NOT NULL,
   FEES NUMBER(8) NOT NULL,
   SCHEDULE VARCHAR2(30) NOT NULL
);

CREATE TABLE PLAYER (
   PLAYER_ID NUMBER(5) PRIMARY KEY,
   PLAYER_NAME VARCHAR2(50) NOT NULL,
   AGE NUMBER(3),
   GENDER VARCHAR2(10),
   CONTACT_NO VARCHAR2(15),
   SPORT_ID NUMBER(5),
   CONSTRAINT FK_PLAYER_SPORT FOREIGN KEY (SPORT_ID)
      REFERENCES SPORT(SPORT_ID)
);

CREATE TABLE COACH (
   COACH_ID NUMBER(5) PRIMARY KEY,
   COACH_NAME VARCHAR2(50) NOT NULL,
   EXPERIENCE NUMBER(3),
   CONTACT_NO VARCHAR2(15),
   SALARY NUMBER(10)
);

CREATE TABLE ADMISSION (
   ADMISSION_ID NUMBER(5) PRIMARY KEY,
   PLAYER_ID NUMBER(5) NOT NULL,
   SPORT_ID NUMBER(5) NOT NULL,
   ADMISSION_DATE DATE,
   CONSTRAINT FK_ADMISSION_PLAYER FOREIGN KEY (PLAYER_ID)
      REFERENCES PLAYER(PLAYER_ID),
   CONSTRAINT FK_ADMISSION_SPORT FOREIGN KEY (SPORT_ID)
      REFERENCES SPORT(SPORT_ID)
);

CREATE TABLE TOURNAMENT (
   TOURNAMENT_ID NUMBER(5) PRIMARY KEY,
   TOURNAMENT_NAME VARCHAR2(50) NOT NULL,
   LOCATION VARCHAR2(50),
   TOURNAMENT_DATE DATE
);

CREATE TABLE ACHIEVEMENT (
   ACHIEVEMENT_ID NUMBER(5) PRIMARY KEY,
   PLAYER_ID NUMBER(5) NOT NULL,
   TOURNAMENT_ID NUMBER(5) NOT NULL,
   POSITION VARCHAR2(20),
   CONSTRAINT FK_ACH_PLAYER FOREIGN KEY (PLAYER_ID)
      REFERENCES PLAYER(PLAYER_ID),
   CONSTRAINT FK_ACH_TOURNAMENT FOREIGN KEY (TOURNAMENT_ID)
      REFERENCES TOURNAMENT(TOURNAMENT_ID)
);

PROMPT Schema created successfully.
